# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger: none

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build_and_push
  displayName: Build and push image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: login
      inputs:
        command: login
        containerRegistry: 'aliyun-registry'
    - task: Docker@2
      displayName: build and push
      inputs:
        containerRegistry: 'aliyun-registry'
        repository: 'xiaoyuzhzh/azure-test'
        command: 'buildAndPush'
        Dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
- stage: Deploy
  displayName: Deploy to Remote Server
  jobs:
  - job: DeployJob
    displayName: Deploy Image
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: SSH@0
      displayName: Pull and Run Docker Image
      inputs:
        sshEndpoint: 'cheap-ecs'
        runOptions: 'inline'
        inline:  |
          # Assuming deploy.sh is in the home directory and executable
          cd ~
          echo 'start deploy'
          source ~/.profile
          echo $DOCKER_USERNAME
          bash ./deploy.sh 19

